//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Build.DotNetNuke.Deployer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Build.DotNetNuke.Deployer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After-Page Full Name &apos;{0}&apos; not found for Page &apos;{1}&apos;..
        /// </summary>
        internal static string AfterPageFullNameNotFoundForTabName {
            get {
                return ResourceManager.GetString("AfterPageFullNameNotFoundForTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After-Page Path &apos;{0}&apos; not found for Page &apos;{1}&apos;..
        /// </summary>
        internal static string AfterPagePathNotFoundForTabName {
            get {
                return ResourceManager.GetString("AfterPagePathNotFoundForTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before-Page Full Name &apos;{0}&apos; not found for Page &apos;{1}&apos;..
        /// </summary>
        internal static string BeforePageFullNameNotFoundForTabName {
            get {
                return ResourceManager.GetString("BeforePageFullNameNotFoundForTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before-Page Path &apos;{0}&apos; not found for Page &apos;{1}&apos;..
        /// </summary>
        internal static string BeforePagePathNotFoundForTabName {
            get {
                return ResourceManager.GetString("BeforePagePathNotFoundForTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file extension: &apos;{0}&apos;..
        /// </summary>
        internal static string FileExtensionNotSupportedForFileName {
            get {
                return ResourceManager.GetString("FileExtensionNotSupportedForFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Page Name &apos;{0}&apos;. Reason: {1}.
        /// </summary>
        internal static string InvalidPageNameWithReason {
            get {
                return ResourceManager.GetString("InvalidPageNameWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module &apos;{0}&apos; not found installed on Target DotNetNuke instance..
        /// </summary>
        internal static string ModuleDefinitionNotFoundForName {
            get {
                return ResourceManager.GetString("ModuleDefinitionNotFoundForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pages found in template..
        /// </summary>
        internal static string NoPagesFoundInTemplate {
            get {
                return ResourceManager.GetString("NoPagesFoundInTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template files to import were uploaded..
        /// </summary>
        internal static string NoTemplateFilesUploaded {
            get {
                return ResourceManager.GetString("NoTemplateFilesUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only accepting one template file at a time..
        /// </summary>
        internal static string OnlyOneTemplateFileAtATime {
            get {
                return ResourceManager.GetString("OnlyOneTemplateFileAtATime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not deleted becase it has child pages (tabID: &apos;{0}&apos;, tabPath: &apos;{1}&apos;)..
        /// </summary>
        internal static string PageNotDeletedChildrenFound {
            get {
                return ResourceManager.GetString("PageNotDeletedChildrenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found with given name: &apos;{0}&apos;..
        /// </summary>
        internal static string PageNotFoundWithGivenName {
            get {
                return ResourceManager.GetString("PageNotFoundWithGivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found with given path: &apos;{0}&apos;..
        /// </summary>
        internal static string PageNotFoundWithGivenPath {
            get {
                return ResourceManager.GetString("PageNotFoundWithGivenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found for tabID: &apos;{0}&apos;, tabPath: &apos;{1}&apos;..
        /// </summary>
        internal static string PageNotFoundWithIdOrPath {
            get {
                return ResourceManager.GetString("PageNotFoundWithIdOrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A page with same path already exists: &apos;{0}&apos; for Page &apos;{1}&apos;..
        /// </summary>
        internal static string PageWithPathAlreadyExistsForTabName {
            get {
                return ResourceManager.GetString("PageWithPathAlreadyExistsForTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Page &apos;{0}&apos; not found for Page &apos;{1}&apos;..
        /// </summary>
        internal static string ParentPageNotFoundForTabName {
            get {
                return ResourceManager.GetString("ParentPageNotFoundForTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a site domain identical to your page path: &apos;{0}&apos;..
        /// </summary>
        internal static string PathDuplicateWithAlias {
            get {
                return ResourceManager.GetString("PathDuplicateWithAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias &apos;{0}&apos; not found..
        /// </summary>
        internal static string PortalAliasNotFound {
            get {
                return ResourceManager.GetString("PortalAliasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; not found on Portal &apos;{1}&apos;. Error Message: &apos;{2}&apos;..
        /// </summary>
        internal static string RoleNameNotFoundOnPortalIDWithMessage {
            get {
                return ResourceManager.GetString("RoleNameNotFoundOnPortalIDWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Page &apos;{0}&apos; is already being used for another page at the same level of the page hierarchy..
        /// </summary>
        internal static string TabExists {
            get {
                return ResourceManager.GetString("TabExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A page &apos;{0}&apos; already exists in the Recycle Bin.  To restore this page use the Recycle Bin..
        /// </summary>
        internal static string TabRecycled {
            get {
                return ResourceManager.GetString("TabRecycled", resourceCulture);
            }
        }
    }
}
